#!/bin/sh
# Regenerate nim.cfg.
#
# This harness links against a logos-delivery checkout and reuses its RESOLVED
# dependency set verbatim, so the code under test is exactly what that checkout
# builds. Nim's .cfg format has no include directive, so the dependency paths
# are inlined here rather than referenced -- which also means nim.cfg is a
# generated, machine-specific file and is not committed.
#
#   LD_ROOT=/path/to/logos-delivery ./tools/gen_nim_cfg.sh
#
# Re-run after bumping logos-delivery's dependencies.
set -eu

if [ -z "${LD_ROOT:-}" ]; then
  echo "error: LD_ROOT is not set." >&2
  echo "  Point it at a logos-delivery checkout that has been built once" >&2
  echo "  (it needs nimble.paths, i.e. 'make' or 'nimble install' has run):" >&2
  echo "    LD_ROOT=~/src/logos-delivery ./tools/gen_nim_cfg.sh" >&2
  exit 2
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
if [ ! -f "$LD_ROOT/nimble.paths" ]; then
  echo "error: $LD_ROOT/nimble.paths not found." >&2
  echo "  That file is produced by logos-delivery's own build; run 'make' there first." >&2
  exit 2
fi

{
  cat <<'HEADER'
# GENERATED by tools/gen_nim_cfg.sh -- do not edit by hand, do not commit.

--mm:refc
--path:"src"

# Relay-only scope: no RLN, so librln/zerokit never reaches the link line.
-d:disable_rln

# The kernel's lightpush path refuses to compile without this.
-d:libp2p_mix_experimental_exit_is_dest

# NOTE: `postgres` and `metrics` are gated with a bare `when defined(X)`, so
# passing `-d:metrics=false` would ENABLE them -- the symbol becomes defined
# whatever its value. They are disabled by being omitted entirely.
#
# metrics stays off on purpose: nim-metrics keeps a process-global registry, so
# N nodes in one process would clobber one series set. Measurement comes from
# in-process taps instead.
#
# threads stays at the Nim 2 default (on): nim-metrics needs getThreadId even
# though the relay tier never spawns a thread.
HEADER
  echo "# LD_ROOT=$LD_ROOT"
  cat "$LD_ROOT/nimble.paths"
  echo "--path:\"$LD_ROOT\""
} > "$ROOT/nim.cfg"
echo "wrote $ROOT/nim.cfg (LD_ROOT=$LD_ROOT)"
